### PR TITLE
Updated to use latest version of Masstransit

### PR DESCRIPTION
**Pull request by BaronVonDrew**
Just updated the package version of Masstransit to the latest and updated NewtonsoftJson to match. All the tests seem to be passing and it's running locally. 

First GitHub pull-request so let me know if anything is completely wrong etc. so I can update.

### CODE REVIEW

**Comment by BaronVonDrew** [comment]
Looks like the AppVeyor build is picking up the MassTransit.TestFramework.dll as a test.dll then failing the tests because there are no fixtures in there.

**Comment by BaronVonDrew** [comment]
*sigh* have just seen that I've forked and merged into master, not the latest develop branch.

**Comment by alexeyzimarev** [comment]
@BaronVonDrew will you be trying again?

**Comment by alexeyzimarev** [comment]
@BaronVonDrew I will fix this in your PR, hold on

**Comment by BaronVonDrew** [comment]
Awesome! Thanks.

**Pull request merged**
